# Generated by Django 6.0.4 on 2026-05-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menucategory_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('city', models.CharField(default='Toshkent', max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman')),
                ('street_address', models.CharField(max_length=255, verbose_name="Ko'cha va uy raqami")),
                ('landmark', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mo'ljal")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('on_way', "Yo'lda (Kuryerda)"), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Yetkazib berish'), ('pickup', 'Olib ketish (Samo-vyvoz)')], default='delivery', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy summa')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yetkazib berish narxi')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Mijoz izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.address')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotilgan narxi')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='main.foods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order')),
            ],
        ),
    ]
